name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

permissions:
  pull-requests: read # permite que o SonarQube decore PRs com resultados de análise

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt' # ou 'temurin'
      - name: Build with Maven
        run: mvn clean install

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@v1
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=fabuniprojecaotag_npj-backend
            -Dsonar.organization=fabuniprojecaotag
        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}